name: Node.js Package

on:
  push:
    tags:
      - 'release/**'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: npm install
        working-directory: ./
      - name: build
        run: npm run build
        working-directory: ./
      - name: publish
        run: npm publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
